-- JournalEvent
ALTER TABLE tu_journal_event DISABLE TRIGGER all;
delete from tu_journal_event; 
INSERT INTO tu_journal_event(jou_eve_id, jou_id, jou_eve_code, jou_eve_desc, jou_eve_desc_en, sort_index, sta_rec_id, dt_cre, usr_cre, dt_upd, usr_upd, jou_eve_grp_id)
    VALUES
    -- Receipts Events
	(1, 5, '01', 'รับชำระตามสัญญา', 'Receive payments according to contract',    1, 1, now(), 'admin', now(), 'admin', null),
	(2, 5, '05', 'ปิดบัญชีก่อนกำหนด', 'Early account closure',                                   1, 1, now(), 'admin', now(), 'admin', null),
	(3, 5, '02', 'ค่าปรับล่าช้า', 'Delay penalty',                                                1, 1, now(), 'admin', now(), 'admin', null),
	(4, 5, '73', 'เงินดาวน์', 'Down payment ',                                                  1, 1, now(), 'admin', now(), 'admin', null),
	(5, 5, '09', 'ค่างวด,ส่วนลด', 'Installment, discount ',                                      1, 1, now(), 'admin', now(), 'admin', null),
	(6, 5, '82', 'ค่าส่งเสริมการขาย', 'Sales promotion fee',                                      1, 1, now(), 'admin', now(), 'admin', null),
	(7, 5, '79', 'ค่าธรรมเนียมการทำสัญญา', 'Contract fee',                                        1, 1, now(), 'admin', now(), 'admin', null),
	(8, 5, '71', 'ค่าติดตาม', 'Follow-up fee',                                                 1, 1, now(), 'admin', now(), 'admin', null),
	(9, 5, '63', 'ค่ายกเลิกสัญญา', 'Contract termination fee',                                  1, 1, now(), 'admin', now(), 'admin', null),
	(10, 5, '65', 'ค่าตรวจสอบ', 'Inspection fee',                                              1, 1, now(), 'admin', now(), 'admin', null),
	(11, 5, '72', 'รับชำระค่าเสียหายทรัพย์สินยึดคืน', 'Receive payment from damages of confiscated assets',  1, 1, now(), 'admin', now(), 'admin', null),
	(12, 5, '68', 'ค่าบริการเก็บรักษาเล่มทะเบียน', 'Fee of keeping car registration book',           1, 1, now(), 'admin', now(), 'admin', null),
	(13, 5, '20', 'เงินประกันการโอนทะเบียน', 'Deposit of register transfer',                      1, 1, now(), 'admin', now(), 'admin', null),
	(14, 5, '21', 'ค่ามัดจำทะเบียน', 'Car registration deposit',                                 1, 1, now(), 'admin', now(), 'admin', null),
	(15, 5, '23', 'ค่ามัดจำทะเบียนป้ายเหลือง', 'Deposit of yellow license plate registration',     1, 1, now(), 'admin', now(), 'admin', null),
	(16, 5, '29', 'ค่าจัดส่งงานทะเบียน', 'Delivery charge to registration',                      1, 1, now(), 'admin', now(), 'admin', null),
	(17, 5, '31', 'ค่าต่อภาษี', 'Tax extension fee',                                           1, 1, now(), 'admin', now(), 'admin', null),
	(18, 5, '32', 'ค่าต่อภาษีและค่าปรับ', 'Tax extension fee and penalty',                        1, 1, now(), 'admin', now(), 'admin', null),
	(19, 5, '33', 'ค่าคัดวงกลม', 'Fee of request for new taxation sign',                      1, 1, now(), 'admin', now(), 'admin', null),
	(20, 5, '34', 'ค่าคัดป้ายเหล็ก', 'Fee of request for new license plate',                     1, 1, now(), 'admin', now(), 'admin', null),
	(21, 5, '35', 'ค่าเปลี่ยนสี', 'Color change expense',                                        1, 1, now(), 'admin', now(), 'admin', null),
	(22, 5, '37', 'ค่าแจ้งย้าย', 'Relocation fee',                                              1, 1, now(), 'admin', now(), 'admin', null),
	(23, 5, '38', 'ค่าโอนทะเบียน 1 ต่อ', 'Fee of car registration transfer( 1 time)',             1, 1, now(), 'admin', now(), 'admin', null),
	(24, 5, '39', 'ค่าโอนทะเบียน 2 ต่อ', 'Fee of car registration transfer( 2 times)',           1, 1, now(), 'admin', now(), 'admin', null),
	(25, 5, '40', 'ค่าปรับโอนล่าช้า', 'Delay penalty of transfer',                              1, 1, now(), 'admin', now(), 'admin', null),
	(26, 5, '41', 'ค่าแจ้งความ', 'Police notification fee',                                  1, 1, now(), 'admin', now(), 'admin', null),
	(27, 5, '42', 'ค่าขอใช้ฯ', 'Fee of use request ',                                        1, 1, now(), 'admin', now(), 'admin', null),
	(28, 5, '44', 'ค่าต่อภาษี 2 ปี และค่าปรับ ค่าตรวจสภาพรถ', '2 years tax extension fee, penalty, car check fee',  1, 1, now(), 'admin', now(), 'admin', null),
	(29, 5, '45', 'ค่าปรับใบสั่ง', 'Ticket penalty',                                        1, 1, now(), 'admin', now(), 'admin', null),
	(30, 5, '46', 'ค่าสมุดคู่มือจดทะเบียน', 'Car registration book fee',                      1, 1, now(), 'admin', now(), 'admin', null),
	(31, 5, '47', 'ค่าโอนทะเบียนเข้าบริษัท', 'Fee of transferring register to company',                      1, 1, now(), 'admin', now(), 'admin', null),
	(32, 5, '48', 'ค่าแจ้งเปลี่ยนผู้ครอบครอง', 'Fee of changing owner ',                      1, 1, now(), 'admin', now(), 'admin', null),
	(33, 5, '49', 'แก้ไขทะเบียนที่จดผิด', 'Edit wrong registration',                        1, 1, now(), 'admin', now(), 'admin', null),
	(34, 5, '53', 'ค่าเปลี่ยนชื่อ-สกุล', 'Name-lastname change fee',                          1, 1, now(), 'admin', now(), 'admin', null),
	(35, 5, '55', 'ค่าเปลี่ยนแปลงที่อยู่', 'Address change fee',                               1, 1, now(), 'admin', now(), 'admin', null),
	(36, 5, '56', 'ค่าระงับการแจ้งย้าย', 'Fee of relocation suspension',                     1, 1, now(), 'admin', now(), 'admin', null),
	(37, 5, '57', 'ค่าเปลี่ยนประเภทรถ', 'Fee of changing car type',                         1, 1, now(), 'admin', now(), 'admin', null),
	(38, 5, '60', 'ค่าตรวจสภาพรถ (รถใหม่)', 'Car check fee ( new car)',                     1, 1, now(), 'admin', now(), 'admin', null),
	(39, 5, '28', 'ค่าปรับปรุงใบคู่มือจดทะเบียน', 'Fee of updating car registration book ',      1, 1, now(), 'admin', now(), 'admin', null),
	(40, 5, '04', 'พักรับไว้เพื่อนำส่งบริษัทประกันฯ', 'Suspend for sending to insurance company',   1, 1, now(), 'admin', now(), 'admin', null),
	(41, 5, '06', 'รับค่าเบี้ยประกันและภาษีอากรเพื่อนำส่งบริษัทประกัน', 'Receive insurance premium and tax to send to insurance company',  1, 1, now(), 'admin', now(), 'admin', null),
	(42, 5, '75', 'ค่าบริการในการดำเนินการ', 'Operation fee',                                1, 1, now(), 'admin', now(), 'admin', null),
	(43, 5, '70', 'ขายทรัพย์สินรอการขาย', 'Sell assets pending for sale',                   1, 1, now(), 'admin', now(), 'admin', null),
	(44, 5, '03', 'ค่าปรับ เช็คคืน/หักบัญชีไม่ผ่าน', 'Penalty of returned cheque/ unsuccessful account debiting', 1, 1, now(), 'admin', now(), 'admin', null),
	(45, 5, '87', 'โปรดคีย์รายละเอียดการรับค่าบริการ', 'Please key detail of receiving service charge',          1, 1, now(), 'admin', now(), 'admin', null),
	(46, 5, '84', 'เงินชดเชยกรณีรถยึด', 'Compensation in case of car confiscation',         1, 1, now(), 'admin', now(), 'admin', null),
	(47, 5, '89', 'รับคืนค่าเบี้ยประกันรถจยย', 'Receive bike insurance premium ',               1, 1, now(), 'admin', now(), 'admin', null),
	(48, 5, '91', 'รับคืนภ.พ.ค้างชำระ', 'Receive unpaid VAT ',                                1, 1, now(), 'admin', now(), 'admin', null),
	(49, 5, '07', 'โปรดคีย์ รายละเอียดการรับ ที่รวมภาษีมูลค่าเพิ่ม', 'Please key receipt detail which includes value added tax',   1, 1, now(), 'admin', now(), 'admin', null),
	(50, 5, '69', 'โปรดคีย์ รายละเอียดการรับ ที่ไม่มีภาษีมูลค่าเพิ่ม', 'Please key receipt detail which doesn’t include value added tax',   1, 1, now(), 'admin', now(), 'admin', null),
	(51, 5, '98', 'รับไว้เพื่อตัดบัญชี', 'Receive to  clear account',                         1, 1, now(), 'admin', now(), 'admin', null),
	(52, 5, '99', 'รับไว้เพื่อรอจ่ายคืน', 'Receive for pending to pay',                      1, 1, now(), 'admin', now(), 'admin', null),
	(53, 5, '80', 'รับเงินค่าธรรมเนียมศาลคืน', 'Receive court fee',                         1, 1, now(), 'admin', now(), 'admin', null),
	(54, 5, '81', 'รับชำระหนี้ตามคำพิพากษา', 'Receive payments according to court judgment',   1, 1, now(), 'admin', now(), 'admin', null),

    -- Payments Events
    (155, 4, '0301', 'ค่าเบี้ยประกันภัยภาคบังคับพรบ.  ประจำงวด', 'Insurance premium of compulsory insurance  period…', 1, 1, now(), 'admin', now(), 'admin', 3),
	(156, 4, '0705', 'ค่าส่งเสริมการขายค่าเบี้ยประกันภัยรถหาย', 'Fee of sales promotion of lost case car insurance premium', 1, 1, now(), 'admin', now(), 'admin', 3),
	(157, 4, '0729', 'ค่าใช้จ่ายในการบังคับคดี   เลขสัญญา', 'Cost of compulsory execution  contract number..', 1, 1, now(), 'admin', now(), 'admin', 3),
	(158, 4, '0731', 'ชำระ ค่าใช้จ่ายเกี่ยวกับงานทะเบียน (งานทะเบียนที่บริษัทรับภาระค่าใช้จ่าย)', 'Pay  registration-involved cost registration that is under control of the company)', 1, 1, now(), 'admin', now(), 'admin', 4),
	(159, 4, '0732', 'ชำระ ค่าใช้จ่ายค่าติดตาม  เลขสัญญา', 'Pay  expense of follow-up            contract number…', 1, 1, now(), 'admin', now(), 'admin', 3),
	(160, 4, '0733', 'ค่าบริการสื่อสารรับส่งข้อมูล', 'Fee of communication', 1, 1, now(), 'admin', now(), 'admin', 3),
	(161, 4, '0736', 'ค่าใช้จ่ายในการติดตาม  เลขสัญญา', 'Expense of follow-up  contract number…', 1, 1, now(), 'admin', now(), 'admin', 3),
	(162, 4, '0743', 'ชำระค่าอากรแสตมป์ อส.4ข ประจำงวด', 'Pay อส.4ข  stamp fee อส.4ข = form of stamp duty payment in cash) period...', 1, 1, now(), 'admin', now(), 'admin', 3),
	(163, 4, '3401', 'ค่าส่งเสริมการขายพิเศษ-ร้านค้า ประจำงวด', 'Special sales promotion fee - shops  period..', 1, 1, now(), 'admin', now(), 'admin', 5),
	(164, 4, '3499', 'ค่าส่งเสริมการาขายพิเศษ-อื่นๆ ประจำงวด', 'Special sales promotion fee - etc.  period..', 1, 1, now(), 'admin', now(), 'admin', 5),
	(165, 4, '3701', 'ชำระค่าเบี้ยประกันภัยรถจักรยานยนต์ ประจำงวดเดือน', 'Pay bike inusurance premium  period..', 1, 1, now(), 'admin', now(), 'admin', 3),
	(166, 4, '3702', 'คืนค่าเบี้ยประกันภัย', 'Return insurance premium', 1, 1, now(), 'admin', now(), 'admin', 3),
	(167, 4, '3801', 'ชำระค่าเบี้ยประกันภัยภาคบังคับ พ.ร.บ. รถจักรยานยนต์ ประจำงวดเดือน ', 'Pay  compulsory insurance premium  period..', 1, 1, now(), 'admin', now(), 'admin', 3),
	(168, 4, '3901', 'คืนเงินประกันความเสียหายเนื่องจากลูกค้าปิดบัญชีแล้ว เลขสัญญา', 'Return security deposit due to account closing  contract number…', 1, 1, now(), 'admin', now(), 'admin', 6),
	(169, 4, '4301', 'ชำระค่าต่อภาษีรถจักรยานยนต์ ตามสัญญาขนส่ง งวดที่ ', 'Pay bike tax extension according to contract of Department of Transportation  installment…..', 1, 1, now(), 'admin', now(), 'admin', 3),
	(170, 4, '4402', 'ชำระค่าใช้จ่ายในการฟ้อง (ค่าจ้างทนาย,ฯลฯ)', 'Pay  prosecution cost  ( lawyer-hire, etc.)', 1, 1, now(), 'admin', now(), 'admin', 3),
	(171, 4, '4501', 'ชำระค่าบริการรับจ้างยึดรถ จำนวน...คัน', 'Pay  car confiscation service charge  numbers of bikes…..', 1, 1, now(), 'admin', now(), 'admin', 3),
	(172, 4, '4502', 'ชำระค่าบริการพิเศษยึดรถ    ประจำงวดเดือน', 'Pay  Special  service charge of car confiscation  period…', 1, 1, now(), 'admin', now(), 'admin', 3),
	(173, 4, '4601', 'โอนเงินประกันรับจ้างยึดงวด ฝากธนาคารชื่อบัญชีผู้รับจ้างยึด', 'Transfer deposit money of car confiscation service ,  deposit money to the bank as an account of confiscator', 1, 1, now(), 'admin', now(), 'admin', 3),
	(174, 4, '9602', 'คืนเงินร้านเนื่องจาก...............', 'Return money to the shop due to……..', 1, 1, now(), 'admin', now(), 'admin', 6),
	(175, 4, '9603', 'คืนเงินมัดจำทะเบียนสัญญา...........', 'Return deposit of contract register', 1, 1, now(), 'admin', now(), 'admin', 6),
	(176, 4, '9604', 'คืนเงินค่าบริการงานทะเบียน', 'Return registration fee', 1, 1, now(), 'admin', now(), 'admin', 6),
	(177, 4, '9605', 'คืนเงินส่วนลดปิดบัญชีก่อนกำหนด', 'Return discount of early account closing', 1, 1, now(), 'admin', now(), 'admin', 3);
select setval('tu_journal_event_jou_eve_id_seq', 200);
ALTER TABLE tu_journal_event ENABLE TRIGGER all;