ALTER TABLE tu_lock_split_type DISABLE TRIGGER all;
delete from tu_lock_split_type;
INSERT INTO tu_lock_split_type(loc_spl_typ_id,loc_spl_typ_code,loc_spl_typ_desc,loc_spl_typ_desc_en,sort_index,sta_rec_id,dt_cre,usr_cre,dt_upd,usr_upd)
VALUES
	-- Receipts Events (active)
	(1, '01', 'รับชำระตามสัญญา', 'Installment', 1, 1, now(), 'admin', now(), 'admin'),
	(2, '02', 'ค่าปรับล่าช้า', 'Penalty', 1, 1, now(), 'admin', now(), 'admin'),
	(3, '03', 'ค่าปรับ เช็คคืน/หักบัญชีไม่ผ่าน', 'Bank fee (bounced cheque)', 1, 1, now(), 'admin', now(), 'admin'),
	(4, '04', 'พักรับไว้เพื่อนำส่งบริษัทประกันฯ', '(1)Insurance premium', 1, 1, now(), 'admin', now(), 'admin'),
	(5, '05', 'ปิดบัญชีก่อนกำหนด', 'Installment', 1, 1, now(), 'admin', now(), 'admin'),
	(6, '06', 'รับค่าเบี้ยประกันและภาษีอากรเพื่อนำส่งบริษัทประกัน', '(2)Compulsory Insurance', 1, 1, now(), 'admin', now(), 'admin'),
	(7, '07', 'โปรดคีย์ รายละเอียดการรับ ที่รวมภาษีมูลค่าเพิ่ม', 'Other received (VAT)', 1, 1, now(), 'admin', now(), 'admin'),
	(8, '09', 'ค่างวด,ส่วนลด', 'Discount', 1, 1, now(), 'admin', now(), 'admin'),
	(9, '19', 'รับชำระตามสัญญา', '', 1, 1, now(), 'admin', now(), 'admin'),
	(10, '20', 'เงินประกันการโอนทะเบียน', 'Deposit of register transfer', 1, 1, now(), 'admin', now(), 'admin'),
	(11, '21', 'ค่ามัดจำทะเบียน', 'Car registration deposit', 1, 1, now(), 'admin', now(), 'admin'),
	(12, '23', 'ค่ามัดจำทะเบียนป้ายเหลือง', 'Deposit of yellow license plate registration', 1, 1, now(), 'admin', now(), 'admin'),
	(13, '28', 'ค่าปรับปรุงใบคู่มือจดทะเบียน', 'Fee of updating car registration book ', 1, 1, now(), 'admin', now(), 'admin'),
	(14, '29', 'ค่าจัดส่งงานทะเบียน', 'Delivery charge to registration', 1, 1, now(), 'admin', now(), 'admin'),
	(15, '31', 'ค่าต่อภาษี', 'Tax extension fee', 1, 1, now(), 'admin', now(), 'admin'),
	(16, '32', 'ค่าต่อภาษีและค่าปรับ', 'Tax extension fee and penalty', 1, 1, now(), 'admin', now(), 'admin'),
	(17, '33', 'ค่าคัดวงกลม', 'Fee of request for new taxation sign', 1, 1, now(), 'admin', now(), 'admin'),
	(18, '34', 'ค่าคัดป้ายเหล็ก', 'Fee of request for new license plate', 1, 1, now(), 'admin', now(), 'admin'),
	(19, '35', 'ค่าเปลี่ยนสี', 'Change color M/C', 1, 1, now(), 'admin', now(), 'admin'),
	(20, '37', 'ค่าแจ้งย้าย', 'Relocation fee', 1, 1, now(), 'admin', now(), 'admin'),
	(21, '38', 'ค่าโอนทะเบียน 1 ต่อ', 'Fee of car registration transfer( 1 time)', 1, 1, now(), 'admin', now(), 'admin'),
	(22, '39', 'ค่าโอนทะเบียน 2 ต่อ', 'Fee of car registration transfer( 2 times)', 1, 1, now(), 'admin', now(), 'admin'),
	(23, '40', 'ค่าปรับโอนล่าช้า', 'Delay penalty of transfer', 1, 1, now(), 'admin', now(), 'admin'),
	(24, '41', 'ค่าแจ้งความ', 'Police notification fee', 1, 1, now(), 'admin', now(), 'admin'),
	(25, '42', 'ค่าขอใช้ฯ', 'Fee of use request ', 1, 1, now(), 'admin', now(), 'admin'),
	(26, '44', 'ค่าต่อภาษี 2 ปี และค่าปรับ ค่าตรวจสภาพรถ', '2 years tax extension fee, penalty, car check fee', 1, 1, now(), 'admin', now(), 'admin'),
	(27, '45', 'ค่าปรับใบสั่ง', 'Ticket penalty', 1, 1, now(), 'admin', now(), 'admin'),
	(28, '46', 'ค่าสมุดคู่มือจดทะเบียน', 'Car registration book fee', 1, 1, now(), 'admin', now(), 'admin'),
	(29, '47', 'ค่าโอนทะเบียนเข้าบริษัท', 'Fee of transferring register to company', 1, 1, now(), 'admin', now(), 'admin'),
	(30, '48', 'ค่าแจ้งเปลี่ยนผู้ครอบครอง', 'Fee of changing owner ', 1, 1, now(), 'admin', now(), 'admin'),
	(31, '49', 'แก้ไขทะเบียนที่จดผิด', 'Edit wrong registration', 1, 1, now(), 'admin', now(), 'admin'),
	(32, '53', 'ค่าเปลี่ยนชื่อ-สกุล', 'Change first/last name', 1, 1, now(), 'admin', now(), 'admin'),
	(33, '55', 'ค่าเปลี่ยนแปลงที่อยู่', 'Change address', 1, 1, now(), 'admin', now(), 'admin'),
	(34, '56', 'ค่าระงับการแจ้งย้าย', 'Fee of relocation suspension', 1, 1, now(), 'admin', now(), 'admin'),
	(35, '57', 'ค่าเปลี่ยนประเภทรถ', 'Change type M/C', 1, 1, now(), 'admin', now(), 'admin'),
	(36, '60', 'ค่าตรวจสภาพรถ (รถใหม่)', 'Car check fee ( new car)', 1, 1, now(), 'admin', now(), 'admin'),
	(37, '61', 'ดอกเบี้ยรับ', 'SUN system', 1, 1, now(), 'admin', now(), 'admin'),
	(38, '63', 'ค่ายกเลิกสัญญา', 'Other income from cancel contract', 1, 1, now(), 'admin', now(), 'admin'),
	(39, '65', 'ค่าตรวจสอบ', 'Other income from Transferred rights', 1, 1, now(), 'admin', now(), 'admin'),
	(40, '68', 'ค่าบริการเก็บรักษาเล่มทะเบียน', 'Fee of keeping car registration book ', 1, 1, now(), 'admin', now(), 'admin'),
	(41, '69', 'โปรดคีย์ รายละเอียดการรับ ที่ไม่มีภาษีมูลค่าเพิ่ม', 'Other received (Non VAT)', 1, 1, now(), 'admin', now(), 'admin'),
	(42, '70', 'ขายทรัพย์สินรอการขาย', 'Sell assets pending for sale', 1, 1, now(), 'admin', now(), 'admin'),
	(43, '71', 'ค่าติดตาม', 'Following fee', 1, 1, now(), 'admin', now(), 'admin'),
	(44, '72', 'รับชำระค่าเสียหายทรัพย์สินยึดคืน', 'Receive payment from damages of confiscated assets', 1, 1, now(), 'admin', now(), 'admin'),
	(45, '73', 'เงินดาวน์', 'Down Payment', 1, 1, now(), 'admin', now(), 'admin'),
	(46, '74', 'เงินประกันความเสียหาย', '', 1, 1, now(), 'admin', now(), 'admin'),
	(47, '75', 'ค่าบริการในการดำเนินการ', 'Insurance service income (operation fee)', 1, 1, now(), 'admin', now(), 'admin'),
	(48, '77', 'ค่าธรรมเนียมธนาคาร', '', 1, 1, now(), 'admin', now(), 'admin'),
	(49, '79', 'ค่าธรรมเนียมการทำสัญญา', 'Service fee (contract fee)', 1, 1, now(), 'admin', now(), 'admin'),
	(50, '80', 'รับเงินค่าธรรมเนียมศาลคืน', 'Receive court fee ', 1, 1, now(), 'admin', now(), 'admin'),
	(51, '81', 'รับชำระหนี้ตามคำพิพากษา', 'Receive payments according to court judgment', 1, 1, now(), 'admin', now(), 'admin'),
	(52, '82', 'ค่าส่งเสริมการขาย', 'Subsidy', 1, 1, now(), 'admin', now(), 'admin'),
	(53, '84', 'เงินชดเชยกรณีรถยึด', 'Compensation', 1, 1, now(), 'admin', now(), 'admin'),
	(54, '87', 'โปรดคีย์รายละเอียดการรับค่าบริการ', 'Commission from Insurance Company', 1, 1, now(), 'admin', now(), 'admin'),
	(55, '88', 'โปรดคีย์รายละเอียดค่าเช่าที่มีภาษีมูลค่าเพิ่ม', 'SUN system', 1, 1, now(), 'admin', now(), 'admin'),
	(56, '89', 'รับคืนค่าเบี้ยประกันรถจยย', 'Compensation (insurance premium)', 1, 1, now(), 'admin', now(), 'admin'),
	(57, '91', 'รับคืนภ.พ.ค้างชำระ', 'Receive unpaid VAT ', 1, 1, now(), 'admin', now(), 'admin'),
	(58, '94', 'เงินประกันความเสียหาย', '', 1, 1, now(), 'admin', now(), 'admin'),
	(59, '96', 'รับคืนเงินทดรองจ่าย', 'SUN system', 1, 1, now(), 'admin', now(), 'admin'),
	(60, '98', 'รับไว้เพื่อตัดบัญชี', 'Receive to clear account', 1, 1, now(), 'admin', now(), 'admin'),
	(61, '99', 'รับไว้เพื่อรอจ่ายคืน', 'Receive for pending to pay ', 1, 1, now(), 'admin', now(), 'admin'),
	(62, 'BD', 'ตัดหนี้สูญ', '', 1, 1, now(), 'admin', now(), 'admin'),
	(63, 'CC', 'ปิดบัญชีงวดสุดท้าย', '', 1, 1, now(), 'admin', now(), 'admin'),
	(64, 'FL', 'ปิดบัญชี', '', 1, 1, now(), 'admin', now(), 'admin'),
	(65, 'XX', 'ปิดบัญชี', '', 1, 1, now(), 'admin', now(), 'admin'),
	(66, 'RD', 'Redemption Fee', 'Redemption Fee', 1, 1, now(), 'admin', now(), 'admin'),

	-- Receipts Events (inactive)
	(80, '00', 'โปรดคีย์ รายละเอียดการรับ', '', 1, 2, now(), 'admin', now(), 'admin'),
	(81, '08', 'ค่าตอบแทนการให้เช่า-', '', 1, 2, now(), 'admin', now(), 'admin'),
	(82, '10', 'รับชำระตามการโอนสิทธิเรียกร้อง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(83, '11', 'ค่าบริการตามสิทธิเรียกร้อง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(84, '12', 'เงินประกันสัญญาโอนสิทธิเรียกร้อง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(85, '13', 'ค่าปรับล่าช้า', '', 1, 2, now(), 'admin', now(), 'admin'),
	(86, '14', 'รับชำระตามการโอนสิทธิเรียกร้อง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(87, '15', 'รับชำระตามการโอนสิทธิเรียกร้องเพื่อปิดบัญชี', '', 1, 2, now(), 'admin', now(), 'admin'),
	(88, '16', 'รับชำระตามการโอนสิทธิเรียกร้อง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(89, '17', 'ค่าธรรมเนียมการขอเบิกใช้วงเงิน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(90, '22', 'ค่าปรับหักบัญชีไม่ผ่าน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(91, '27', 'ค่าตรวจสอบการอายัดทะเบียน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(92, '30', 'ค่าอากร', '', 1, 2, now(), 'admin', now(), 'admin'),
	(93, '36', 'ค่ารับป้ายแผ่นเหล็ก', '', 1, 2, now(), 'admin', now(), 'admin'),
	(94, '43', 'ค่าเปลี่ยนสี พร้อมโอนทะเบียน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(95, '50', 'ค่าเปลี่ยนเครื่อง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(96, '51', 'ค่าเปลี่ยนเครื่องและปรับ', '', 1, 2, now(), 'admin', now(), 'admin'),
	(97, '52', 'ค่าปรับใบเสร็จเปลี่ยนเครื่องล่าช้า', '', 1, 2, now(), 'admin', now(), 'admin'),
	(98, '54', 'ค่าใบเสร็จเปลี่ยนสีล่าช้า', '', 1, 2, now(), 'admin', now(), 'admin'),
	(99, '58', 'ค่าเปลี่ยนชื่อ กรุ๊ปลีส จาก  บจก. เป็น บมจ.', '', 1, 2, now(), 'admin', now(), 'admin'),
	(100, '59', 'ค่าบริการ-งานทะเบียน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(101, '62', 'ค่าธรรมเนียมจัดการ', '', 1, 2, now(), 'admin', now(), 'admin'),
	(102, '66', 'รายได้-ส่วนลดเบี้ยประกัน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(103, '67', 'ค่าธรรมเนียมจัดการสินเชื่อเงินสด', '', 1, 2, now(), 'admin', now(), 'admin'),
	(104, '76', 'ขายทรัพย์สินตามสัญญาเช่าแบบลีสซิ่ง', '', 1, 2, now(), 'admin', now(), 'admin'),
	(105, '78', 'ค่าบริการตัวแทนเก็บเงิน', '', 1, 2, now(), 'admin', now(), 'admin'),
	(106, '83', 'เงินดาวน์', '', 1, 2, now(), 'admin', now(), 'admin'),
	(107, '85', 'ค่าบริการประกันภัยไตรมาสที่ N/ปีพ.ศ.', '', 1, 2, now(), 'admin', now(), 'admin'),
	(108, '86', 'รายได้-ส่วนลดเบี้ยประกันภัย', '', 1, 2, now(), 'admin', now(), 'admin'),
	(109, '95', 'เงินประกันทรัพย์สินฝากขาย', '', 1, 2, now(), 'admin', now(), 'admin'),
	(110, '97', 'รับไว้เพื่อหาเลขสัญญา', '', 1, 2, now(), 'admin', now(), 'admin'),
	(111, 'AS', 'ทรัพย์สินรอการขาย', '', 1, 2, now(), 'admin', now(), 'admin'),
	(112, 'CA', 'สินเชื่อเงินสด', '', 1, 2, now(), 'admin', now(), 'admin'),
	(113, 'RR', '', '', 1, 2, now(), 'admin', now(), 'admin'),
	(114, 'บบ', '', '', 1, 2, now(), 'admin', now(), 'admin');

update tu_lock_split_type set loc_spl_typ_desc_en = loc_spl_typ_desc where loc_spl_typ_desc_en = '';
select setval('tu_lock_split_type_loc_spl_typ_id_seq', 200);
ALTER TABLE tu_lock_split_type ENABLE TRIGGER all;