alter table ts_ref_table rename column ref_tab_field1_cus_id to ref_tab_field1_cus_typ_id;
alter table ts_ref_table rename column ref_tab_field2_cus_id to ref_tab_field2_cus_typ_id;
alter table ts_ref_table rename column ref_tab_field3_cus_id to ref_tab_field3_cus_typ_id;
alter table ts_ref_table rename column ref_tab_field4_cus_id to ref_tab_field4_cus_typ_id;
alter table ts_ref_table rename column ref_tab_field5_cus_id to ref_tab_field5_cus_typ_id;