ALTER TABLE tu_lock_split_type DISABLE TRIGGER all;
delete from tu_lock_split_type;
INSERT INTO tu_lock_split_type(loc_spl_typ_id,loc_spl_typ_code,loc_spl_typ_desc,loc_spl_typ_desc_en,sort_index,sta_rec_id,dt_cre,usr_cre,dt_upd,usr_upd)
VALUES
	(1, '01', 'รับชำระตามสัญญา', 'Payment Contract',                                    1, 1, now(), 'admin', now(), 'admin'),
	(2, '05', 'ปิดบัญชีก่อนกำหนด', 'Closing Early',                                    1, 1, now(), 'admin', now(), 'admin'),
	(3, '02', 'ค่าปรับล่าช้า', 'Delay Fines',                                    1, 1, now(), 'admin', now(), 'admin'),
	(4, '73', 'เงินดาวน์', 'down payment',                                    1, 1, now(), 'admin', now(), 'admin'),
	(5, '09', 'ค่างวด,ส่วนลด', 'Annuities, discounts',                                    1, 1, now(), 'admin', now(), 'admin'),
	(6, '82', 'ค่าส่งเสริมการขาย', 'Promotional value',                                    1, 1, now(), 'admin', now(), 'admin'),
	(7, '79', 'ค่าธรรมเนียมการทำสัญญา', 'Fee contract',                                    1, 1, now(), 'admin', now(), 'admin'),
	(8, '71', 'ค่าติดตาม', 'Follow up',                                    1, 1, now(), 'admin', now(), 'admin'),
	(9, '63', 'ค่ายกเลิกสัญญา', 'The contract cancellation',                                    1, 1, now(), 'admin', now(), 'admin'),
	(10, '65', 'ค่าตรวจสอบ', 'Check the',                                    1, 1, now(), 'admin', now(), 'admin'),
	(11, '72', 'รับชำระค่าเสียหายทรัพย์สินยึดคืน', 'Payment of compensation for property expropriation',                                    1, 1, now(), 'admin', now(), 'admin'),
	(12, '68', 'ค่าบริการเก็บรักษาเล่มทะเบียน', 'Fee shelf registration book',                                    1, 1, now(), 'admin', now(), 'admin'),
	(13, '20', 'เงินประกันการโอนทะเบียน', 'Insurance money transfer register',                                    1, 1, now(), 'admin', now(), 'admin'),
	(14, '21', 'ค่ามัดจำทะเบียน', 'Registration fee',                                    1, 1, now(), 'admin', now(), 'admin'),
	(15, '23', 'ค่ามัดจำทะเบียนป้ายเหลือง', 'Deposits up Yellow Label',                                    1, 1, now(), 'admin', now(), 'admin'),
	(16, '29', 'ค่าจัดส่งงานทะเบียน', 'Registration Fee',                                    1, 1, now(), 'admin', now(), 'admin'),
	(17, '31', 'ค่าต่อภาษี', 'The tax value',                                    1, 1, now(), 'admin', now(), 'admin'),
	(18, '32', 'ค่าต่อภาษีและค่าปรับ', 'The taxes and fines',                                    1, 1, now(), 'admin', now(), 'admin'),
	(19, '33', 'ค่าคัดวงกลม', 'Copy the circle',                                    1, 1, now(), 'admin', now(), 'admin'),
	(20, '34', 'ค่าคัดป้ายเหล็ก', 'Copy the steel plate',                                    1, 1, now(), 'admin', now(), 'admin'),
	(21, '35', 'ค่าเปลี่ยนสี', 'The color change',                                    1, 1, now(), 'admin', now(), 'admin'),
	(22, '37', 'ค่าแจ้งย้าย', 'The Relocation',                                    1, 1, now(), 'admin', now(), 'admin'),
	(23, '38', 'ค่าโอนทะเบียน 1 ต่อ', '1 registration fee per transfer',                                    1, 1, now(), 'admin', now(), 'admin'),
	(24, '39', 'ค่าโอนทะเบียน 2 ต่อ', 'The transfer of registration per second',                                    1, 1, now(), 'admin', now(), 'admin'),
	(25, '40', 'ค่าปรับโอนล่าช้า', 'Fines transfer delay',                                    1, 1, now(), 'admin', now(), 'admin'),
	(26, '41', 'ค่าแจ้งความ', 'The notification',                                    1, 1, now(), 'admin', now(), 'admin'),
	(27, '42', 'ค่าขอใช้ฯ', 'The request states',                                    1, 1, now(), 'admin', now(), 'admin'),
	(28, '44', 'ค่าต่อภาษี 2 ปี และค่าปรับ ค่าตรวจสภาพรถ', 'On the tax two years and fines, vehicle inspectors.',                                    1, 1, now(), 'admin', now(), 'admin'),
	(29, '45', 'ค่าปรับใบสั่ง', 'Orders Fines',                                    1, 1, now(), 'admin', now(), 'admin'),
	(30, '46', 'ค่าสมุดคู่มือจดทะเบียน', 'The booklets listed',                                    1, 1, now(), 'admin', now(), 'admin'),
	(31, '47', 'ค่าโอนทะเบียนเข้าบริษัท', 'Transfer to company registration',                                    1, 1, now(), 'admin', now(), 'admin'),
	(32, '48', 'ค่าแจ้งเปลี่ยนผู้ครอบครอง', 'Changing the occupant',                                    1, 1, now(), 'admin', now(), 'admin'),
	(33, '49', 'แก้ไขทะเบียนที่จดผิด', 'Fix up the wrong note',                                    1, 1, now(), 'admin', now(), 'admin'),
	(34, '53', 'ค่าเปลี่ยนชื่อ-สกุล', 'Change the Name -',                                    1, 1, now(), 'admin', now(), 'admin'),
	(35, '55', 'ค่าเปลี่ยนแปลงที่อยู่', 'The address change',                                    1, 1, now(), 'admin', now(), 'admin'),
	(36, '56', 'ค่าระงับการแจ้งย้าย', 'The suspension of moves',                                    1, 1, now(), 'admin', now(), 'admin'),
	(37, '57', 'ค่าเปลี่ยนประเภทรถ', 'Change the type of car',                                    1, 1, now(), 'admin', now(), 'admin'),
	(38, '60', 'ค่าตรวจสภาพรถ (รถใหม่)', 'Check the condition of the car (new cars).',                                    1, 1, now(), 'admin', now(), 'admin'),
	(39, '28', 'ค่าปรับปรุงใบคู่มือจดทะเบียน', 'The updated Leaf registered guide',                                    1, 1, now(), 'admin', now(), 'admin'),
	(40, '04', 'พักรับไว้เพื่อนำส่งบริษัทประกันฯ', 'Rooms are to be submitted to the insurance company.',                                    1, 1, now(), 'admin', now(), 'admin'),
	(41, '06', 'รับค่าเบี้ยประกันและภาษีอากรเพื่อนำส่งบริษัทประกัน', 'Get insurance premiums and taxes to be remitted insurers.',                                    1, 1, now(), 'admin', now(), 'admin'),
	(42, '75', 'ค่าบริการในการดำเนินการ', 'Service in Action',                                    1, 1, now(), 'admin', now(), 'admin'),
	(43, '70', 'ขายทรัพย์สินรอการขาย', 'Sales of foreclosed properties',                                    1, 1, now(), 'admin', now(), 'admin'),
	(44, '03', 'ค่าปรับ เช็คคืน/หักบัญชีไม่ผ่าน', 'Fines returned check / debit verification.',                                    1, 1, now(), 'admin', now(), 'admin'),
	(45, '87', 'โปรดคีย์รายละเอียดการรับค่าบริการ', 'Please key details be charged.',                                    1, 1, now(), 'admin', now(), 'admin'),
	(46, '84', 'เงินชดเชยกรณีรถยึด', 'Car based compensation case',                                    1, 1, now(), 'admin', now(), 'admin'),
	(47, '89', 'รับคืนค่าเบี้ยประกันรถจยย', 'Return the car insurance premium motorcycle',                                    1, 1, now(), 'admin', now(), 'admin'),
	(48, '91', 'รับคืนภ.พ.ค้างชำระ', 'Returns Tr. May. Arrears.',                                    1, 1, now(), 'admin', now(), 'admin'),
	(49, '07', 'โปรดคีย์ รายละเอียดการรับ ที่รวมภาษีมูลค่าเพิ่ม', 'Please get key details VAT',                                    1, 1, now(), 'admin', now(), 'admin'),
	(50, '69', 'โปรดคีย์ รายละเอียดการรับ ที่ไม่มีภาษีมูลค่าเพิ่ม', 'Please get key details Without VAT',                                    1, 1, now(), 'admin', now(), 'admin'),
	(51, '98', 'รับไว้เพื่อตัดบัญชี', 'Welcome to deferred',                                    1, 1, now(), 'admin', now(), 'admin'),
	(52, '99', 'รับไว้เพื่อรอจ่ายคืน', 'Get paid to wait',                                    1, 1, now(), 'admin', now(), 'admin'),
	(53, '80', 'รับเงินค่าธรรมเนียมศาลคืน', 'Fees paid nights',                                    1, 1, now(), 'admin', now(), 'admin'),
	(54, '81', 'รับชำระหนี้ตามคำพิพากษา', 'The judgment debt',                                    1, 1, now(), 'admin', now(), 'admin');
select setval('tu_lock_split_type_loc_spl_typ_id_seq', 200);
ALTER TABLE tu_lock_split_type ENABLE TRIGGER all;