package com.nokor.efinance.core.shared.credit;

public interface CreditControlEntityField {
		
		String BLACKLISTED = "BLACKLISTED";
		String SUSPICIUS_PHONE_NUMBER = "SUSPICIUS_PHONE_NUMBER";		
		String RESIDENCE_A_THE_REGISTRATION_ADDRESS = "RESIDENCE_A_THE_REGISTRATION_ADDRESS";				
		String DELINQUENCY_CHECK = "DELINQUENCY_CHECK";
		String MAXIMUM_CUMULATED_DEBT_RATION = "MAXIMUM_CUMULATED_DEBT_RATION";
				
		String AGE = "AGE";
		String EMPLOYMENT = "EMPLOYMENT";
		String NET_INCOME = "NET_INCOME";
		String HOUSE_OWNERSHIP = "HOUSE_OWNERSHIP";
		String OLD_LESSEE = "OLD_LESSEE";		
		String GENDER = "GENDER";		
		String GUARANTOR = "GUARANTOR";
		String REFERENCE = "REFERENCE";	
		String BLACKLIST_STATUS_LESSEE = "BLACKLIST_STATUS_LESSEE";
		String BLACKLIST_STATUS_GUARANTOR = "BLACKLIST_STATUS_GUARANTOR";
		String BLACKLIST_STATUS_REFERENCE = "BLACKLIST_STATUS_REFERENCE";		
		String MIN_LIVING_PERIOD = "MIN_LIVING_PERIOD";
		String LOAN_TO_INCOME = "LOAN_TO_INCOME";
		String NUMBER_OF_ACTIVIVE_LOAN = "NUMBER_OF_ACTIVIVE_LOAN";
		String MIN_CREDIT_SCORE = "MIN_CREDIT_SCORE";
		String CREDIT_LIMIT = "CREDIT_LIMIT";
		String DUPLICATED_PHONE = "DUPLICATED_PHONE";
}
