delete from tu_document_group;
INSERT INTO tu_document_group(doc_grp_id, doc_grp_code, doc_grp_desc, doc_grp_desc_en, sort_index, sta_rec_id, dt_cre, usr_cre, dt_upd, usr_upd)
VALUES 
    (1, 'EVIDENCE', 'Evidence and Document', 'Evidence and Document', 1, 1, now(), 'admin', now(), 'admin'),
    (2, 'CONTRACT', 'Contract',              'Contract',              2, 1, now(), 'admin', now(), 'admin'),
    (3, 'NOTICE',   'Notice',                'Notice',                3, 1, now(), 'admin', now(), 'admin'),
    (4, 'RECEIPT',  'Receipt/Invoice',       'Receipt/Invoice',       4, 1, now(), 'admin', now(), 'admin'),
    (5, 'LETTER',   'Letter',                'Letter',                5, 1, now(), 'admin', now(), 'admin'),
    (6, 'LEGAL',    'Legal',                 'Legal',                 6, 1, now(), 'admin', now(), 'admin'),
    (7, 'TOOL',     'Tool',                  'Tool',                  7, 1, now(), 'admin', now(), 'admin'),
    (8, 'RECDOC',   'Received document',     'Received document',     8, 1, now(), 'admin', now(), 'admin');
select setval('tu_document_group_doc_grp_id_seq', 20);

delete from tu_document;
INSERT INTO tu_document(doc_id, doc_code, doc_desc, doc_desc_en,  dogrp_id, sort_index, sta_rec_id, dt_cre, usr_cre, dt_upd, usr_upd, 
						doc_bl_mandatory, doc_sta_id, app_typ_id, doc_bl_allow_change_update_asset, doc_bl_expire_date_required, 
       					doc_bl_field_check, doc_bl_issue_date_required, doc_bl_reference_required, doc_bl_submit_credit_bureau) 
VALUES 
    (1,  'NOTLIS',    'Noticed list',                            'Noticed list',                            1, 1,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (2,  'GIVPOWER',  'Given Power of attortney',                'Given Power of attortney',                1, 2,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (3,  'RECPRI',    'Recieved primary daily report',           'Recieved primary daily report',           1, 3,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (4,  'RECCRIME',  'Recieved crime report',                   'Recieved crime report',                   1, 4,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (5,  'LIDCARD',   'Lessee''s ID Card',                       'Lessee''s ID Card',                       1, 5,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (6,  'LHOUREG',   'Lessee''s House registration',            'Lessee''s House registration',            1, 6,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (7,  'RIDCARD',   'Rider''s ID card',                        'Rider''s ID card',                        1, 7,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (8,  'RHOUREG',   'Rider''s House registration',             'Rider''s House registration',             1, 8,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (9,  'OWNTRA',    'Ownership transference form',             'Ownership transference form',             1, 9,  1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (10, 'WAICOMAGR', 'Waived compensation agreement',           'Waived compensation agreement',           1, 10, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (11, 'KEY',       'Key',                                     'Key',                                     1, 11, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (12, 'ACONTRACT', 'Leasing contract',                        'Leasing contract',                        2, 12, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (13, 'GAGR',      'Guarantor agreement',                     'Guarantor agreement',                     2, 13, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (14, 'EXTNOT',    'Extension notice',                        'Extension notice',                        3, 14, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (15, 'LASDUEDAT', 'Last due date notice',                    'Last due date notice',                    3, 15, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (16, 'AUCINVLET', 'Auction invitation letter',               'Auction invitation letter',               3, 16, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (17, 'ASSLAUNOT', 'Asset launching notification',            'Asset launching notification',            3, 17, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (18, 'TEMREC',    'Temporary receipt',                       'Temporary receipt',                       4, 18, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (19, 'RECEIPT',   'Receipt',                                 'Receipt',                                 4, 19, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (20, 'TAXINV',    'Tax invoice',                             'Tax invoice',                             4, 20, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (21, 'OVE1M',     'Overdue 1 month letter',                  'Overdue 1 month letter',                  5, 21, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (22, 'OVE2M',     'Overdue 2 month letter',                  'Overdue 2 month letter',                  5, 22, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (23, 'OVE3M',     'Overdue 3 month letter',                  'Overdue 3 month letter',                  5, 23, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (24, 'REDLET',    'Redemption letter',                       'Redemption letter',                       5, 24, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (25, 'AUCDEBT',   'Auction result letter (Debt pressing)',   'Auction result letter (Debt pressing)',   5, 25, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (26, 'AUCREFUND', 'Auction result letter (Refund)',          'Auction result letter (Refund)',          5, 26, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (27, 'CLAAUCION', 'Claimed result letter (Auction)',         'Claimed result letter (Auction)',         5, 27, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (28, 'CLALOST',   'Claimed result letter (Lost)',            'Claimed result letter (Lost)',            5, 28, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (29, 'CLADAM',    'Claimed result letter (Damaged)',         'Claimed result letter (Damaged)',         5, 29, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (30, 'CLADEATH',  'Claimed result letter (Death)',           'Claimed result letter (Death)',           5, 30, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (31, 'JUDDEBT',   'Judged result letter (Debt pressing)',    'Judged result letter (Debt pressing)',    5, 31, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (32, 'GRPPOWER',  'Group power of attorney',                 'Group power of attorney',                 6, 32, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (33, 'POWSEIZE',  'Power of attorney (Seized)',              'Power of attorney (Seized)',              6, 33, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (34, 'POWLOST',   'Power of attorney (Lost)',                'Power of attorney (Lost)',                6, 34, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (35, 'POWOT',     'Power of attorney (OT)',                  'Power of attorney (OT)',                  6, 35, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (36, 'NCBSTATUS', 'Non-obligation certificate (NCB status)', 'Non-obligation certificate (NCB status)', 6, 36, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (37, 'LEGALNCB',  'Non-obligation certificate',              'Non-obligation certificate',              6, 37, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (38, 'DLTTRAREQ', 'DLT transference request form',           'DLT transference request form',           6, 38, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (39, 'POSTRAREQ', 'Possessor transference request form',     'Possessor transference request form',     6, 39, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (40, 'POSTRANOT', 'Possessor transference notice',           'Possessor transference notice',           6, 40, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (41, 'CUSCARD',   'Customer card',                           'Customer card',                           7, 41, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (42, 'PAYINSLIP', 'Payment pay in slip',                     'Payment pay in slip',                     7, 42, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
    (43, 'AIDCARD',   'ID copy',                                 'ID copy',                                 8, 43, 1,  now(), 'admin', now(), 'admin', true,  1, 1, false, false, false, false, false, false),
	(44, 'NCB',       'NCB',                                     'NCB',                                     8, 44, 1,  now(), 'admin', now(), 'admin', true,  1, 1, false, false, false, false, false, false),
	(45, 'APPFORM',   'Application form',                        'Application form',                        8, 45, 1,  now(), 'admin', now(), 'admin', true,  1, 1, false, false, false, false, false, false),
	(46, 'SALSLIP',   'Salary slip',                             'Salary slip', 							8, 46, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(47, 'BNKSTAT',   'Bank statement',                          'Bank statement',                          8, 47, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(48, 'HOUPHO',    'House Photo',                             'House Photo',                             8, 48, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(49, 'FIELDCH',   'Field check',                             'Field check',                             8, 49, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(50, 'HOUREG',    'House registration', 				     'House registration',                      8, 50, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(51, 'GAGREEM',   'Guarantor agreement ',                    'Guarantor agreement ',                    8, 51, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(52, 'GIDCARD',   'Guarantor ID copy',                       'Guarantor ID copy',                       8, 52, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false),
	(53, 'MOTOPIC',   'Motorbike Picture',                       'Motorbike Picture',                       8, 53, 1,  now(), 'admin', now(), 'admin', false, 1, 1, false, false, false, false, false, false);
select setval('tu_document_doc_id_seq', 100);
	